--- #YAML:1.0
name: XML-Generator-RSS10
version: 0.01
author: David Rolsky <autarch@urth.org>
abstract: Generate SAX events for RSS
license: perl
requires:
  Test::More: 0
provides: {}
generated_by: Module::Build version 0.25
